server:
  port: 8080

spring:
  main:
    lazy-initialization: true
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000 # where in ()
    show-sql: true
    open-in-view: false

logging:
  file:
    name: /app/log/app.log
  level:
    org.hibernate.type: trace

file:
  base-path: